// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAGroupAlphaSpring26.Data;

#nullable disable

namespace SAGroupAlphaSpring26.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260217025958_TestingPieceTypesInput2.0")]
    partial class TestingPieceTypesInput20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PieceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Enemy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Map"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
