// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAGroupAlphaSpring26.Data;

#nullable disable

namespace SAGroupAlphaSpring26.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260217235012_PrepareForAzureDeploy")]
    partial class PrepareForAzureDeploy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SetID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieceTypeID");

                    b.HasIndex("SetID");

                    b.ToTable("Pieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default Description",
                            ImagePath = "/images/Cleric.png",
                            Name = "Cleric",
                            PieceTypeID = 1,
                            Price = 0.00m,
                            SetID = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Default Description",
                            ImagePath = "/images/testMap.png",
                            Name = "Default Dungeon",
                            PieceTypeID = 2,
                            Price = 0.00m,
                            SetID = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Default Description",
                            ImagePath = "/images/GoblinChief.png",
                            Name = "Goblin Chief",
                            PieceTypeID = 1,
                            Price = 0.00m,
                            SetID = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Default Description",
                            ImagePath = "/images/chest.png",
                            Name = "Basic Chest",
                            PieceTypeID = 1,
                            Price = 0.00m,
                            SetID = 1
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PieceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Map"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Structure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Object"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shop"
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieceId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PieceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchaseID")
                        .HasColumnType("int");

                    b.Property<int>("SetID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2026, 2, 17, 17, 50, 12, 338, DateTimeKind.Local).AddTicks(998),
                            Notes = "Production Test Session",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Base Set",
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expansion 1",
                            Price = 4.99m
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Marketplaces");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceID")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<int>("zIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieceID");

                    b.HasIndex("SessionID");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            IsVisible = true,
                            Name = "Cleric",
                            PieceID = 1,
                            SessionID = 1,
                            X = 50.0,
                            Y = 15.0,
                            zIndex = 3
                        },
                        new
                        {
                            Id = 5,
                            IsVisible = true,
                            Name = "Cleric",
                            PieceID = 1,
                            SessionID = 1,
                            X = 50.0,
                            Y = 20.0,
                            zIndex = 4
                        },
                        new
                        {
                            Id = 1,
                            IsVisible = true,
                            Name = "Default Dungeon",
                            PieceID = 2,
                            SessionID = 1,
                            X = 0.0,
                            Y = 0.0,
                            zIndex = 0
                        },
                        new
                        {
                            Id = 2,
                            IsVisible = true,
                            Name = "Goblin Chief",
                            PieceID = 3,
                            SessionID = 1,
                            X = 50.0,
                            Y = 5.0,
                            zIndex = 1
                        },
                        new
                        {
                            Id = 3,
                            IsVisible = false,
                            Name = "Basic Chest",
                            PieceID = 4,
                            SessionID = 1,
                            X = 50.0,
                            Y = 10.0,
                            zIndex = 2
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 17, 17, 50, 12, 338, DateTimeKind.Local).AddTicks(950),
                            Email = "tjackson@students.ntc.edu",
                            Username = "Tristan"
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.PieceType", "PieceType")
                        .WithMany()
                        .HasForeignKey("PieceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Set", "Set")
                        .WithMany("Pieces")
                        .HasForeignKey("SetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PieceType");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Purchase", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.User", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Token", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Session", "Session")
                        .WithMany("Tokens")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Set", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
