// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAGroupAlphaSpring26.Data;

#nullable disable

namespace SAGroupAlphaSpring26.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260308213628_seedDataMovedToDataContext")]
    partial class seedDataMovedToDataContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PieceSet", b =>
                {
                    b.Property<int>("PiecesListId")
                        .HasColumnType("int");

                    b.Property<int>("SetsId")
                        .HasColumnType("int");

                    b.HasKey("PiecesListId", "SetsId");

                    b.HasIndex("SetsId");

                    b.ToTable("PieceSet");
                });

            modelBuilder.Entity("PieceUser", b =>
                {
                    b.Property<int>("OwnedPiecesId")
                        .HasColumnType("int");

                    b.Property<int>("OwnersId")
                        .HasColumnType("int");

                    b.HasKey("OwnedPiecesId", "OwnersId");

                    b.HasIndex("OwnersId");

                    b.ToTable("PieceUser");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PieceTypeID");

                    b.ToTable("Pieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No description provided",
                            ImagePath = "/images/testMap.png",
                            Name = "Default Dungeon",
                            PieceTypeID = 2,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "No description provided",
                            ImagePath = "/images/Cleric.png",
                            Name = "Cleric",
                            PieceTypeID = 1,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "No description provided",
                            ImagePath = "/images/GoblinChief.png",
                            Name = "Goblin Chief",
                            PieceTypeID = 5,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "No description provided",
                            ImagePath = "/images/chest.png",
                            Name = "Basic Chest",
                            PieceTypeID = 4,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "No description provided",
                            ImagePath = "/images/bardTest.png",
                            Name = "Bard",
                            PieceTypeID = 1,
                            Price = 0.00m
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PieceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Map"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Structure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Object"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shop"
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.SaleLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PieceID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieceID");

                    b.HasIndex("SaleID");

                    b.ToTable("SaleLines");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2026, 3, 8, 16, 36, 25, 672, DateTimeKind.Local).AddTicks(3766),
                            Notes = "Local Test Session",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceID")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ZIndex")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PieceID");

                    b.HasIndex("SessionId");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Dungeon",
                            PieceID = 2,
                            SessionId = 1,
                            Visibility = true,
                            X = 0m,
                            Y = 0m,
                            ZIndex = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cleric",
                            PieceID = 1,
                            SessionId = 1,
                            Visibility = true,
                            X = 50m,
                            Y = 15m,
                            ZIndex = 3m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Goblin Chief",
                            PieceID = 5,
                            SessionId = 1,
                            Visibility = true,
                            X = 50m,
                            Y = 5m,
                            ZIndex = 1m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Basic Chest",
                            PieceID = 4,
                            SessionId = 1,
                            Visibility = false,
                            X = 50m,
                            Y = 10m,
                            ZIndex = 2m
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "local@demo.com",
                            Username = "LocalDM"
                        });
                });

            modelBuilder.Entity("PieceSet", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", null)
                        .WithMany()
                        .HasForeignKey("PiecesListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PieceUser", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", null)
                        .WithMany()
                        .HasForeignKey("OwnedPiecesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.PieceType", "PieceType")
                        .WithMany("Pieces")
                        .HasForeignKey("PieceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PieceType");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Sale", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.SaleLine", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Sale", "Sale")
                        .WithMany("SaleLines")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Token", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Session", "Session")
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceType", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Sale", b =>
                {
                    b.Navigation("SaleLines");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
