// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAGroupAlphaSpring26.Data;

#nullable disable

namespace SAGroupAlphaSpring26.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieceId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.CartItemSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItemSets");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PieceTypeID");

                    b.ToTable("Pieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No description provided",
                            ImagePath = "/images/testMap.png",
                            IsArchived = false,
                            Name = "Default Dungeon",
                            PieceTypeID = 2,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "No description provided",
                            ImagePath = "/images/Cleric.png",
                            IsArchived = false,
                            Name = "Cleric",
                            PieceTypeID = 1,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "No description provided",
                            ImagePath = "/images/GoblinChief.png",
                            IsArchived = false,
                            Name = "Goblin Chief",
                            PieceTypeID = 5,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "No description provided",
                            ImagePath = "/images/chest.png",
                            IsArchived = false,
                            Name = "Basic Chest",
                            PieceTypeID = 4,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "No description provided",
                            ImagePath = "/images/bardTest.png",
                            IsArchived = false,
                            Name = "Bard",
                            PieceTypeID = 1,
                            Price = 0.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "No description provided",
                            ImagePath = "/images/BetaMap1.png",
                            IsArchived = false,
                            Name = "Beta Dungeon",
                            PieceTypeID = 2,
                            Price = 5.00m
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceSets", b =>
                {
                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<int>("SetId")
                        .HasColumnType("int");

                    b.HasKey("PieceId", "SetId");

                    b.HasIndex("SetId");

                    b.ToTable("PieceSets");

                    b.HasData(
                        new
                        {
                            PieceId = 2,
                            SetId = 1
                        },
                        new
                        {
                            PieceId = 5,
                            SetId = 1
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PieceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Map"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Structure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Object"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shop"
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.SaleLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PieceID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.Property<int?>("SetID")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PieceID");

                    b.HasIndex("SaleID");

                    b.HasIndex("SetID");

                    b.ToTable("SaleLines");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsArchived = false,
                            LastUpdated = new DateTime(2026, 4, 25, 14, 58, 6, 804, DateTimeKind.Local).AddTicks(7719),
                            Name = "Test Session",
                            Notes = "Local Test Session",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsArchived = false,
                            LastUpdated = new DateTime(2026, 4, 25, 14, 58, 6, 804, DateTimeKind.Local).AddTicks(7723),
                            Name = "Test Session 2",
                            Notes = "Local Test Session 2",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsArchived = false,
                            Name = "Evans Beginner Pack",
                            Price = 0.00m
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieceID")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<bool>("Visibility")
                        .HasColumnType("bit");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ZIndex")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PieceID");

                    b.HasIndex("SessionId");

                    b.ToTable("Tokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Dungeon",
                            Notes = "",
                            PieceID = 1,
                            SessionId = 1,
                            Visibility = true,
                            X = 0m,
                            Y = 0m,
                            ZIndex = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cleric",
                            Notes = "",
                            PieceID = 2,
                            SessionId = 1,
                            Visibility = true,
                            X = 50m,
                            Y = 15m,
                            ZIndex = 3m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Goblin Chief",
                            Notes = "",
                            PieceID = 3,
                            SessionId = 1,
                            Visibility = true,
                            X = 50m,
                            Y = 5m,
                            ZIndex = 1m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Basic Chest",
                            Notes = "",
                            PieceID = 4,
                            SessionId = 1,
                            Visibility = false,
                            X = 50m,
                            Y = 10m,
                            ZIndex = 2m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beta Dungeon",
                            Notes = "",
                            PieceID = 6,
                            SessionId = 2,
                            Visibility = true,
                            X = 0m,
                            Y = 0m,
                            ZIndex = 0m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cleric",
                            Notes = "",
                            PieceID = 2,
                            SessionId = 2,
                            Visibility = true,
                            X = 50m,
                            Y = 15m,
                            ZIndex = 3m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cleric",
                            Notes = "",
                            PieceID = 2,
                            SessionId = 2,
                            Visibility = true,
                            X = 50m,
                            Y = 5m,
                            ZIndex = 1m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cleric",
                            Notes = "",
                            PieceID = 2,
                            SessionId = 2,
                            Visibility = true,
                            X = 50m,
                            Y = 10m,
                            ZIndex = 2m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Goblin Chief",
                            Notes = "",
                            PieceID = 3,
                            SessionId = 2,
                            Visibility = true,
                            X = 50m,
                            Y = 5m,
                            ZIndex = 1m
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "local@demo.com",
                            FirstName = "Local",
                            IsAdmin = true,
                            LastName = "DM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKlUfZW0M90IVWp+rS8P741RjV0eTwyqv3VMrlUSmWydJ33AVt02GStShKlKhTU1qg=="
                        },
                        new
                        {
                            Id = 2,
                            Email = "evankvang@gmail.com",
                            FirstName = "Evan",
                            IsAdmin = false,
                            LastName = "Vang",
                            PasswordHash = "AQAAAAIAAYagAAAAELQQXzDxRORX+ouA3P+HMhgr6Lih9Mgk7H5AhwM/WH4UOkTHZaxp3rCO4bvsSh8S8g=="
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.UserPieces", b =>
                {
                    b.Property<int>("PieceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PieceId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPieces");

                    b.HasData(
                        new
                        {
                            PieceId = 1,
                            UserId = 1
                        },
                        new
                        {
                            PieceId = 2,
                            UserId = 1
                        },
                        new
                        {
                            PieceId = 3,
                            UserId = 1
                        },
                        new
                        {
                            PieceId = 4,
                            UserId = 1
                        },
                        new
                        {
                            PieceId = 5,
                            UserId = 1
                        },
                        new
                        {
                            PieceId = 6,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.CartItem", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany("CartItems")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.CartItemSet", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Set", "Set")
                        .WithMany("CartItemSets")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany("CartItemSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.PieceType", "PieceType")
                        .WithMany("Pieces")
                        .HasForeignKey("PieceTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PieceType");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceSets", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany("Sets")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Set", "Set")
                        .WithMany("PiecesList")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Sale", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.SaleLine", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany("SaleLines")
                        .HasForeignKey("PieceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Sale", "Sale")
                        .WithMany("SaleLines")
                        .HasForeignKey("SaleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Set", "Set")
                        .WithMany("SaleLines")
                        .HasForeignKey("SetID");

                    b.Navigation("Piece");

                    b.Navigation("Sale");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Token", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.Session", "Session")
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.UserPieces", b =>
                {
                    b.HasOne("SAGroupAlphaSpring26.Models.Piece", "Piece")
                        .WithMany("Owners")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAGroupAlphaSpring26.Models.User", "User")
                        .WithMany("OwnedPieces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Piece", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Owners");

                    b.Navigation("SaleLines");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.PieceType", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Sale", b =>
                {
                    b.Navigation("SaleLines");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Session", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.Set", b =>
                {
                    b.Navigation("CartItemSets");

                    b.Navigation("PiecesList");

                    b.Navigation("SaleLines");
                });

            modelBuilder.Entity("SAGroupAlphaSpring26.Models.User", b =>
                {
                    b.Navigation("CartItemSets");

                    b.Navigation("CartItems");

                    b.Navigation("OwnedPieces");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
